import { Box, } from '@chakra-ui/react'
import Head from 'next/head'
import Index1 from '../src/components/app/Home1/Index'
import Header from '../src/components/core/Header/Header'
import Footer from './../src/components/core/Footer/Footer';
export default function Home() {
  return (
    <>
      <Head>
        <title>Gamblers Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon.svg" />
      </Head>
      <Index1/>
      <Footer/>
    </>
  )
}
